# Generated by Django 4.1.2 on 2023-12-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_post_id_alter_profile_id_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
