# Generated by Django 4.1.2 on 2023-12-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
    ]
