# Generated by Django 4.1.2 on 2023-12-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_bio_alter_profile_image_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.DeleteModel(
            name='Bio',
        ),
    ]
